package config

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// InitOptions controls the initial config written by Initialize.
type InitOptions struct {
	Keystore   string
	DeviceID   string
	StateFile  string
	ClientType string
	Force      bool
}

// GenerateDeviceID returns a cryptographically random 128-bit device ID in
// the controller's required 32-character uppercase hexadecimal format.
func GenerateDeviceID() (string, error) {
	return generateDeviceID(rand.Reader)
}

func generateDeviceID(source io.Reader) (string, error) {
	var raw [16]byte
	if _, err := io.ReadFull(source, raw[:]); err != nil {
		return "", fmt.Errorf("generate device_id: %w", err)
	}
	return strings.ToUpper(hex.EncodeToString(raw[:])), nil
}

// PrepareInitialConfig applies initialization defaults and validates them
// without touching the filesystem. Callers can run it before interactive or
// external setup steps to avoid side effects for invalid options.
func PrepareInitialConfig(opts InitOptions) (*Config, error) {
	if opts.Keystore == "" {
		opts.Keystore = "./ids-passkey.keystore"
	}
	if opts.StateFile == "" {
		opts.StateFile = "./state.enc"
	}
	if opts.ClientType == "" {
		opts.ClientType = "client"
	}
	if opts.DeviceID == "" {
		var err error
		opts.DeviceID, err = GenerateDeviceID()
		if err != nil {
			return nil, err
		}
	}

	cfg := &Config{
		Keystore:   opts.Keystore,
		DeviceID:   opts.DeviceID,
		BaseURL:    DefaultBaseURL,
		Platform:   "Mac",
		AppID:      DefaultAppID,
		ClientType: opts.ClientType,
		StateFile:  opts.StateFile,
		LogLevel:   "info",
		Inbound: Inbound{
			SOCKS5: Listener{Enabled: true, Listen: "127.0.0.1:1080"},
			HTTP:   Listener{Enabled: true, Listen: "127.0.0.1:8080"},
		},
	}
	// applyDefaults fills Web.Listen (and guards every future default)
	// before validation; validate also canonicalizes Web.Listen.
	cfg.applyDefaults()
	if err := cfg.validate(); err != nil {
		return nil, err
	}
	return cfg, nil
}

// Initialize writes a ready-to-use config. Client mode is the default because
// it can bind the generated device ID as a trusted terminal after the first
// successful login. Existing files are preserved unless Force is true.
func Initialize(path string, opts InitOptions) (*Config, error) {
	if path == "" {
		return nil, errors.New("config path is required")
	}
	cfg, err := PrepareInitialConfig(opts)
	if err != nil {
		return nil, err
	}
	data := renderInitialConfig(cfg)
	if err := writeConfigFile(path, data, opts.Force); err != nil {
		return nil, err
	}
	return cfg, nil
}

func renderInitialConfig(cfg *Config) []byte {
	q := strconv.Quote
	return []byte(fmt.Sprintf(`# Generated by geektrust init. Keep device_id stable after the first login.
keystore = %s
device_id = %s
base_url = %s
platform = %s
client_type = %s
state_file = %s
gateways = []
dns = []
log_level = %s

[inbound.socks5]
enabled = true
listen = %s

[inbound.http]
enabled = true
listen = %s

[web]
enabled = %t
listen = %s
`,
		q(cfg.Keystore), q(cfg.DeviceID), q(cfg.BaseURL), q(cfg.Platform),
		q(cfg.ClientType), q(cfg.StateFile), q(cfg.LogLevel),
		q(cfg.Inbound.SOCKS5.Listen), q(cfg.Inbound.HTTP.Listen),
		cfg.WebEnabled(), q(cfg.Web.Listen),
	))
}

func writeConfigFile(path string, data []byte, force bool) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}

	if !force {
		f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
		if err != nil {
			if errors.Is(err, os.ErrExist) {
				return fmt.Errorf("config %s already exists; use --force to replace it", path)
			}
			return fmt.Errorf("create config: %w", err)
		}
		if err := writeAndClose(f, data); err != nil {
			_ = os.Remove(path)
			return err
		}
		return nil
	}

	tmp, err := os.CreateTemp(dir, ".geektrust-config-*")
	if err != nil {
		return fmt.Errorf("create temporary config: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("secure temporary config: %w", err)
	}
	if err := writeAndClose(tmp, data); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace config: %w", err)
	}
	return nil
}

func writeAndClose(f *os.File, data []byte) error {
	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return fmt.Errorf("write config: %w", err)
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return fmt.Errorf("sync config: %w", err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("close config: %w", err)
	}
	return nil
}
